# Generated by Django 2.0.7 on 2018-08-02 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_remove_comment_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptchaStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.CharField(max_length=32)),
                ('response', models.CharField(max_length=32)),
                ('hashkey', models.CharField(max_length=40, unique=True)),
                ('expiration', models.DateTimeField()),
            ],
        ),
    ]
