# Generated by Django 2.0.7 on 2018-08-02 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_captchastore'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CaptchaStore',
        ),
    ]
